# Generated by Django 4.0.4 on 2022-05-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issues_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500, null=True)),
                ('comments', models.CharField(max_length=2500, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('issues_image', models.ImageField(null=True, upload_to='uploads/')),
                ('gender', models.TextField(max_length=2500, null=True)),
                ('issues', models.TextField(max_length=2500, null=True)),
            ],
        ),
    ]
